### ISSUE TITLE
install appli

### ISSUE THREAD

**Issue by Olivier2099** [Bessouat40/foodcop#10]
préparer un tuto et éventuellement des scripts pour déployer l'appli sur PC.

**Objectif** : Pourvoir déployer l'appli pour les premiers tests utilisateur

**Comment by Bessouat40** [comment]
Ajout d'un fichier run.sh à exécuter

**Comment by Bessouat40** [comment]
Modification : ajouter une branche sans système d'authentification pour pouvoir tester simplement l'application en local.
